#- este PRIMER bloque mejor no tocarlo -----------------------------------------
#- este PRIMER bloque mejor no tocarlo -----------------------------------------
#- (salvo la última linea)
project:   
  title: "trabajo_BigData_individual"
  type: website          
  output-dir: docs       
  preview:
    port: 4445
    browser: true
    watch-inputs: true
    navigate: true
  
#- para incluir el logo de la UV en la pestaña del navegador
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "imagenes/mundo.jpg" />
     
#- hace el rendered documento (.html) autocontenido  
# embed-resources: true  

#- agrandar imágenes: https://quarto.org/docs/output-formats/html-lightbox-figures.html
lightbox: true



#- anchor sections (links en las secciones del rendered document)
anchor-sections: true

#- otros enlaces (que aparecerán debajo del TOC)
other-links:
  - text: Web del curso
    href: https://perezp44.github.io/intro-ds-25-26-web/
  - text: Trabajos de mis compañeros
    href: https://perezp44.github.io/intro-ds-25-26-web/05-trabajos-estudiantes.html 
  - text: Repo del trabajo
    href: https://github.com/ipfuster/trabajo_BigData_individual     
  - text: Más artículos míos de GEOPOLÍTICA
    href: https://www.linkedin.com/pulse/groenlandia-espejo-de-la-geopol%C3%ADtica-actual-isabel-p-fuster-yvosf 

#- este SEGUNDO bloque puedes tocarlo pero no hace falta -----------------------
#- este SEGUNDO bloque puedes tocarlo pero no hace falta -----------------------


#- opciones para el índice (TOC)
toc: true
toc-depth: 3
toc-location: right    
toc-title: "Índice"   #---

#- hace que los links se abren en pestañas nuevas
link-external-newwindow: true 

#- Cross-references
crossref:
  fig-title: Gráfico  # (default is "Figure")
  tbl-title: Tabla    # (default is "Table")

#- Posicion de los fig-captions
fig-cap-location: bottom

#- opciones para las imágenes hechas con código   
#fig-height: 5
#fig-width: 5
fig-format: png
fig-dpi: 300


#- opciones para los chunks de código --
#- https://quarto.org/docs/output-formats/html-code.html
code-copy: true
code-overflow: wrap   #- {wrap, scroll}
code-fold: show
code-line-numbers: true

#- embeed the source document 
code-tools: true
code-link: true

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  

#- el output de los chunks del .qmd van a los panes
editor_options: 
  chunk_output_type: console

#- licencia: https://quarto.org/docs/reference/formats/html.html#metadata
license: CC BY


# Default execute options
execute:
  echo: true
  eval: true
  message: false
  warning: false
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog   (AQUI!!!!!)
                 #- https://quarto.org/docs/projects/code-execution.html#freeze




#- ESTRUCTURA/layout de la página WEB -------   

website:
  title: "Conflictos bélicos"            #- hay q cambiarlo  AQUI!!!!
  favicon: imagenes/mundo.jpg     #- 
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    pinned: true
    logo: "imagenes/mundo.jpg"   
    background: "#3F5F3F"    
    foreground: "#3D3D3D"    
    left: 
      - icon: fa-globe
        href: index.html
    right:
      - text: "Trabajo individual IPF"     
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/ipfuster   
      - icon: envelope
        url: "mailto:<tipunfus@alumni.uv.es>" 
      - icon: linkedin
        url: https://www.linkedin.com/in/isabel-punter-fuster/

        
  page-footer:
    border: true
    background: "#8d2634"       
    left: "© 2025 Isabel Punter"   
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/ipfuster     
      - icon: envelope
        url: "mailto:ipunfus@alumni.uv.es"           
    
    

#- FORMATO -------   


format:
  html:
    page-layout: full
    theme: 
      - sandstone #- {cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti}
    css: 
      - assets/styles.css
    mainfont: Arial
    highlight-style: a11y   #-

   

#- opciones de lenguaje
lang: es  #- castellano {es, en}    https://quarto.org/docs/authoring/language.html
language: assets/_my_language-es.yml  #- por si quieres usar tus propios "términos" en castellano
